### PR TITLE
Added FOLLOW pagination type.

### PR DESCRIPTION
**Pull request by scottccoates**
This only follows pages (dynamically) after crawling all of the links in the base page. If you have any interest in this PR, I can flesh out the implementation and docs.

### CODE REVIEW

**Comment by Pmant** [comment]
as far as I understand you would provide a Xpath pointing to the next page. Most sites using pagination have a "next page" link which disappears on the last page. This would be very useful if you wanted to scrape all pages instead of first n.

**Comment by bezkos** [comment]
@holgerd77 I tested this PR and seems to work fine (done only 1-2 simple modifications with DDS 0.11.2). I think its good to merge it cause it solves the problem with dynamic max_page pagination of DDS.

**Comment by holgerd77** [comment]
@bezkos Thought about that, I'll do a slightly different implementation allowing for more flexibility on pagination, but this will be integrated into next release.

Cheers
Holger

**Comment by bezkos** [comment]
@holgerd77 Based on this PR, i implemented one form of ASP/JS pagination for DDS. I can't do new PR cause i use a previous version of DDS for it. If u interested for it, i can write here the new code so u can append this pagination in next version of DDS.

**Comment by holgerd77** [comment]
Hi @bezkos, thanks for the offer! As I mentioned in the comment before, I already implemented this in the latest development branch, will be released any time soon.

Greetings
Holger

**Comment by bezkos** [comment]
@holgerd77 This PR is for HTML pagination, I implemented ASP/JS pagination as i mention above.

**Comment by holgerd77** [comment]
Hi @bezkos, sorry for the late answer: what exactly do you mean with ASP/JS pagination? Can you give an example use case and shortly describe, how this is then handled with your implementation/how it works in DDS?

**Comment by bezkos** [comment]
@holgerd77 You can see this kind of pagination here
https://stackoverflow.com/questions/10218581/using-scrapy-to-scrap-asp-net-website-with-javascript-buttons-and-ajax-requests
To handle this pagination, u need to scrape some fields from GET/POST requests, add some extra params and use FORMREQUESTS to get data.

**Comment by holgerd77** [comment]
@bezkos Hmm, at first glance I'm not seeing any point, why this can't be done with the existing DDS implementation

**Comment by bezkos** [comment]
@holgerd77 Did u achieve to scrape a site like this with existing DDS options?

**Pull request closed without merging**
