### PR TITLE
Get scrapy port

### PR DESCRIPTION
**Pull request by DeanSherwin**
Allow usage of different scrapyd http port

### CODE REVIEW

**Comment by holgerd77** [comment]
Thanks for the PR, sorry, can't emphasize work on this library that much atm, but will try to review in the next 1-2 weeks.

One question: ``Scrapyd`` settings are different from Scrapy settings? So the port is not receivable through ``settings = get_project_settings()``?

Also, the commit history is extremely blurry with unnecessary double commits, can you please rebase this and squash all the commits into one with a meaningful commit message? Thanks.

**Comment by DeanSherwin** [comment]
Hi Holger,

I think so. I thought I'd be able to use get_project_settings() but couldn't figure out how. - both of the default settings for Scrapyd and Scrapy will have individual settings which list port 6800. However, it is the daemon's settings (scrapyd) where this should be configurable. In my scenario I needed to have multiple instances of Scrapyd running on different ports because I was running multiple DDS projects on one server from different virtualenvs. As 6800 was hardcoded into DDS, changing the scrapyd.conf file had no effect. If a use has no scrapyd.conf file it will default to 6800 anyway.

I will rebase these commits into one meaningful one. 

Dean

**Comment by holgerd77** [comment]
Ok, thanks.

**Comment by DeanSherwin** [comment]
Done.

**Comment by holgerd77** [comment]
Looks good, thanks for the PR!

**Pull request merged**
