### PR TITLE
adding missing migrations

### PR DESCRIPTION
**Pull request by bashu**

### CODE REVIEW

**Comment by takdavid** [comment]
+1

**Comment by holgerd77** [comment]
Hmm, what's the use of having this in the example project? A simple ``python manage.py migrate`` will just do the DB synchronization with the current status of the data structure?

**Comment by takdavid** [comment]
No, in a new clean project it doesn't. The `makemigrations` doesn't recognize open_news as migratable, and so `migrate` doesn't find anything...

**Comment by holgerd77** [comment]
I just cloned the ``master`` branch of the repo into a fresh folder, went to the ``example_project`` folder and ran ``python manage.py migrate`` and everthing worked. Or am I not getting the point here?

**Comment by bashu** [comment]
@takdavid was correct, I have the problem

**Pull request closed without merging**
