### PR TITLE
Add explicit on_delete argument to be compatible for Django 2.0.

### PR DESCRIPTION
**Pull request by ryokamiya**
Django 2 requires explicit on_delete argument as per the following page.

https://docs.djangoproject.com/en/2.0/releases/2.0/

"The on_delete argument for ForeignKey and OneToOneField is now required in models and migrations. Consider squashing migrations so that you have fewer of them to update."

This fix will suppress the Django 2.0 warnings in Django 1.x and fix the compatibility issue for Django 2.

### CODE REVIEW

**Comment by holgerd77** [comment]
Thanks for the PR. 😄  This will also need a migration for users to update their models, doesn't it?

**Comment by ryokamiya** [comment]
Thank YOU for this great library and prompt reply to my PR!

The default has been the CASCADE so there's no impact to the migration files.

Ref:
django.db.models.fields.related
```python
        if on_delete is None:
            warnings.warn(
                "on_delete will be a required arg for %s in Django 2.0. Set "
                "it to models.CASCADE on models and in existing migrations "
                "if you want to maintain the current default behavior. "
                "See https://docs.djangoproject.com/en/%s/ref/models/fields/"
                "#django.db.models.ForeignKey.on_delete" % (
                    self.__class__.__name__,
                    get_docs_version(),
                ),
                RemovedInDjango20Warning, 2)
            on_delete = CASCADE
```

I just double checked by running makemigrations BEFORE I make changes, but I found the following possibly missing migrations.

```zsh
% python manage.py makemigrations                                                                      (git)-[master]
Migrations for 'dynamic_scraper':
  ../dynamic_scraper/migrations/0026_auto_20180202_0632.py
    - Alter field checker_type on checker
    - Alter field scraped_obj_attr on checker
    - Alter field level on log
    - Alter field mark_with_type on logmarker
    - Alter field content_type on requestpagetype
    - Alter field dont_filter on requestpagetype
    - Alter field meta on requestpagetype
    - Alter field method on requestpagetype
    - Alter field render_javascript on requestpagetype
    - Alter field request_type on requestpagetype
    - Alter field scraped_obj_attr on requestpagetype
    - Alter field runtime_type on schedulerruntime
    - Alter field attr_type on scrapedobjattr
    - Alter field checker_scheduler_conf on scrapedobjclass
    - Alter field scraper_scheduler_conf on scrapedobjclass
    - Alter field max_items_read on scraper
    - Alter field max_items_save on scraper
    - Alter field pagination_append_str on scraper
    - Alter field pagination_page_replace on scraper
```

**Comment by ryokamiya** [comment]
Sorry it's me again.. It seems my fix needs more changes.

I just realised that I ran the makemigrations and test from Django 1.11 to Django 2 upgraded environment. (I was using your library in Django 1.11 then upgraded to Django 2 with this fix.)
When I ran the makemigrations in fresh environment, I encountered with the issue on running the cumulative migrations starting from 0001_initial.py and so on. We need changes to the old migration files as well.

The issue is mentioned here: https://code.djangoproject.com/ticket/25981

I will add these later to this PR. Sorry.

**Comment by holgerd77** [comment]
No problem, good if this is slowly worked out.

**Comment by holgerd77** [comment]
Generally from my experience from having done this for various ``Django`` versions, adding support for a new version (probably especially for a major ``1.x`` to ``2.x`` version change, always requires work on various fronts.

**Comment by holgerd77** [comment]
For self-reference: https://docs.djangoproject.com/en/2.0/releases/2.0/

**Comment by holgerd77** [comment]
Hi, thanks for your ongoing work, great! 😄 

To maintain a readable commit history not being bloated up to much please use rebasing to keep the history clean. I you haven't done this before, I strongly recommend doing a local copy of the whole repo before, this can go wrong easily.

For rebasing, you need an up-to-date ``master`` branch. Then start interactive rebasing with ``git rebase -i master`` from your working branch.

Instead of reverting those "Added migrations" commit, you can then just drop both commits.

Also please meld the later "Removing b" commit into the previous one with "squash".

You can then push your changes with ``git push --force origin fix_django2``.

Thanks!

**Comment by ryokamiya** [comment]
Hi, thank you for advices!
I'm not very good at git commands especially when things are going out of control.. I just made another fresh PR if that works better.

https://github.com/holgerd77/django-dynamic-scraper/pull/104

(Let me also try those commands you suggests for my own learning as well. Thank you very much.)

Thanks.

**Comment by holgerd77** [comment]
Closed in favor of https://github.com/holgerd77/django-dynamic-scraper/pull/104.

**Pull request closed without merging**
